Restore version 0.1.9 Vero files written to two partitions like RPi Vero boot partition has installer only Added support for cloning Vero to SD card or USB Vero filesystem can be tar.xz, tar or raw files

diff --git a/osmc-restore b/osmc-restore
--- a/osmc-restore
+++ b/osmc-restore
@@ -1,27 +1,21 @@
 #! /bin/bash
 
-# A script to restore backups to removable media. It will also format an
+# A script to restore backups to removable media. It will also format a USB stick or
 # SD card suitable for OSMC and restore the system and boot partitions appropriately
 
-# Copyright (c) Graham Horner, 2017. 
+# Copyright (c) Graham Horner, 2017-19. 
 # Feel free to use and/or modify for any non-commercial purposes.
 # No warranty as to fitness of purpose or suitability
 # is given or should be inferred.
 
 # Any comments or bug reports to discourse.osmc.tv.
 
-VERSION='0.1.7' ## add check for dependencies and handle mmcblk devices
-set +x
+VERSION='0.1.9' ## much improved for Vero
+#set -x
 # check if this is being run as root
 if (( $(/usr/bin/id -u) != 0 )); then
 	echo Must be run as root!
 	exit 1
-fi
-
-# check we have xz
-if ! xz --version &> /dev/null; then
-	GETDEPENDS=1
-	echo -e "\nThis script needs xz but I can't find it\nTry: sudo apt-get install xz-utils (or similar)\n"
 fi
 
 # check we have parted
@@ -34,6 +28,12 @@ fi
 if ! rsync --version &> /dev/null; then
 	GETDEPENDS=1
 	echo -e "\nThis script needs rsync but I can't find it\nTry: sudo apt-get install rsync (or similar)\n"
+fi
+
+# check we have pv
+if ! pv --version &> /dev/null; then
+	GETDEPENDS=1
+	echo -e "\nThis script needs pv but I can't find it\nTry: sudo apt-get install pv (or similar)\n"
 fi
 
 if (($GETDEPENDS)); then exit 0; fi
@@ -60,38 +60,18 @@ if [ -z $1 ]; then
 	exit 1
 fi
 
+#echo $BACKUPDIR
 CLONE=0
 LIVE=0
 PARTStoRESTORE=(boot system)
 
-# see if $BACKUPDIR is a device
-if [[ $(lsblk -lo NAME,TYPE | grep "$BACKUPDIR.*disk"$ ) ]]; then
-	CLONE=1
-	BACKUPDEV=($(lsblk -lo NAME,TYPE | grep "$BACKUPDIR.*disk"$ ))
-	echo Going to copy ${BACKUPDEV[0]}
-elif ! [[ "$BACKUPDIR" =~ ^/ ]]; then
-	# make BACKUPDIR path absolute
-	BACKUPDIR="$PWD/$BACKUPDIR"
-	# tidy it
-	BACKUPDIR=$( cd "$BACKUPDIR" && pwd )
-else
-	if [ "$BACKUPDIR" == "/" ]; then
-		CLONE=1
-		LIVE=1
-		echo Going to copy the working SD card
-	else
-		# remove a trailing slash
-		BACKUPDIR=${BACKUPDIR%/}
-	fi
-fi
-
 # check if we are only copying one partition
 for source in ${PARTStoRESTORE[@]}; do
 	if [[ "$BACKUPDIR" =~ "$source"$ ]]; then
-		echo $BACKUPDIR
+		echo Restoring only $BACKUPDIR
 		PARTStoRESTORE=($source)
 		BACKUPDIR=${BACKUPDIR%/$source}
-		echo now $BACKUPDIR
+		#echo now $BACKUPDIR
 		if [ -z "$BACKUPDIR" ]; then
 			CLONE=1
 			LIVE=1
@@ -100,27 +80,49 @@ for source in ${PARTStoRESTORE[@]}; do
 	fi
 done
 
-VERO=0
-if [[ $BACKUPDIR =~ "vero" ]]; then 
-	VERO=1
-elif [[ $BACKUPDIR != '/' ]] && [ $(ls "$BACKUPDIR/system/boot" | wc -l) \> 0 ]; then
-	VERO=1
-fi
-
-if (($VERO)); then
-	PARTStoRESTORE=(system)
-	if (($LIVE)); then
-		echo Can\'t clone live vero partition
-		exit 0
+# see if $BACKUPDIR is a device
+if [[ $(lsblk -lo NAME,TYPE | grep "$BACKUPDIR.*disk"$ ) ]] && ! [[ "$BACKUPDIR" =~ ^\. ]] ; then
+	CLONE=1
+	BACKUPDEV=($(lsblk -lo NAME,TYPE | grep "$BACKUPDIR.*disk"$ ))
+	echo Going to copy ${BACKUPDEV[0]}
+elif ! [[ "$BACKUPDIR" =~ ^/ ]]; then
+	# make BACKUPDIR path absolute
+	BACKUPDIR="$PWD/$BACKUPDIR"
+	# tidy it
+	BACKUPDIR=$( pushd "$BACKUPDIR" > /dev/null && pwd && popd > /dev/null )
+else
+	if [ "$BACKUPDIR" == "/" ]; then
+		CLONE=1
+		LIVE=1
+		echo Going to copy the working filesystem
+	else
+		# remove a trailing slash
+		BACKUPDIR=${BACKUPDIR%/}
 	fi
 fi
 
-SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+VERO=0
+if [[ ${BACKUPDIR^^} =~ "VERO" ]]; then 
+	VERO=1
+elif ((LIVE)) && [[ $(cat /proc/cmdline) =~ vero ]]; then
+	VERO=1
+elif ! [ -d "$BACKUPDIR/boot" ] && ! (($CLONE)); then
+	VERO=1
+fi
+
+SCRIPTDIR="$( pushd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd && popd > /dev/null )"
 
 BACKUPFOUND=0
+#echo $BACKUPDIR
 
 if [ -d "$BACKUPDIR" ] || (($CLONE)); then
 	for source in ${PARTStoRESTORE[@]}; do
+
+		if [ $source == "boot" ] && (($VERO)); then
+			BACKUPFOUND=$(($BACKUPFOUND + 1))
+			continue
+		fi
+
 		if (($CLONE)); then
 			if (($LIVE)); then
 				if [ $source == "system" ]; then
@@ -132,20 +134,19 @@ if [ -d "$BACKUPDIR" ] || (($CLONE)); then
 			else
 				# partition is defined by device ID so re-mount it
 				if [ $source == "system" ]; then
-					SRCDEV=/dev/$BACKUPDIR2
+					SRCDEV="/dev/$BACKUPDIR"2
 				elif [ $source == "boot" ]; then
-					SRCDEV=/dev/$BACKUPDIR1
+					SRCDEV="/dev/$BACKUPDIR"1
 				fi
-				umount $SRCDEV || echo Cannot unmount $SRCDEV; exit 1
+				umount $SRCDEV || echo Cannot unmount $SRCDEV
 				mkdir -p /media/sdcard/$source
-				if [ $(ls $source | wc -l) == 0 ]; then mount $SRCDEV /media/sdcard/$source || exit 1; fi
+				if [ $(ls /media/sdcard/$source | wc -l) == 0 ]; then mount $SRCDEV /media/sdcard/$source || exit 1; fi
 				# else we assume it's already mounted, (eg if last backup didn't complete)
-				# but lets just check (SHOULD'NT NEED THIS, NOW)
+				# but lets just check (SHOULDN'T NEED THIS, NOW)
 				if ! findmnt -l | grep "^/media/sdcard/$source " &> /dev/null; then
 					echo /media/sdcard/$source is not a mount point
 					exit 1
 				fi
-				BACKUPDIR=/media/sdcard
 			fi
 			BACKUPFOUND=1
 		elif [ -d "$BACKUPDIR"/$source ]; then
@@ -155,6 +156,7 @@ if [ -d "$BACKUPDIR" ] || (($CLONE)); then
 		fi
 	done
 	if ! (($BACKUPFOUND)); then exit 0; fi
+	if ((CLONE)) && !((LIVE)); then BACKUPDIR=/media/sdcard; fi
 else
 	echo Cannot find $BACKUPDIR, please check
 	exit 0
@@ -185,6 +187,10 @@ while ! lsblk | grep "^$MEDIA " > /dev/null; do
 	fi
 done
 
+if [[ $MEDIA =~ mmcblk.* ]]; then
+	PARTPREFIX="p"
+fi
+
 # trim partition number if both partitions to be restored
 PARTNO=0
 if [[ $MEDIA =~ (mmcblk[0-9])p([0-9])$ ]]; then
@@ -193,12 +199,13 @@ if [[ $MEDIA =~ (mmcblk[0-9])p([0-9])$ ]]; then
 elif ! [[ $MEDIA =~ mmcblk.* ]] && [[ $MEDIA =~ (.*)([0-9])$ ]]; then
 	DEVICE=${BASH_REMATCH[1]}
 	PARTNO=${BASH_REMATCH[2]}
+else
+	DEVICE=$MEDIA
 fi
 if [ ${#PARTStoRESTORE[@]} \> 1 ] || (($FORMAT)); then
 		MEDIA=$DEVICE
 		PARTNO=0
 fi
-
 
 function format(){
 	read -n1 -rsp "Going to erase all of /dev/$MEDIA, press Y to continue ... " ANSWER
@@ -234,13 +241,13 @@ function format(){
 		PART1=256MiB
 	fi
 
-	echo Formatting SD card $MEDIA
-	if (($VERO)); then
-		parted -s /dev/$MEDIA -- mklabel msdos mkpart primary fat32 $BLANK -1s
+	if [ 'p' == $PARTPREFIX ]; then
+		echo Formatting SD card $MEDIA
 	else
-		parted -s /dev/$MEDIA mklabel msdos mkpart primary fat32 $BLANK $PART1 \
-			&& parted -s /dev/$MEDIA -- mkpart primary ext4 $PART1 -1s
+		echo Formatting USB stick $MEDIA
 	fi
+	parted -s /dev/$MEDIA mklabel msdos mkpart primary fat32 $BLANK $PART1 \
+		&& parted -s /dev/$MEDIA -- mkpart primary ext4 $PART1 -1s
 	# refresh the partitions in the kernel, but that also mounts them
 	# if there was already a filesystem there
 	partprobe /dev/"$MEDIA"
@@ -252,71 +259,45 @@ function format(){
 	parted /dev/"$MEDIA" set 1 lba on
 	umount /dev/"$MEDIA$PARTPREFIX"1 2> /dev/null
 	mkfs.vfat -F 32 -s 4 -I /dev/"$MEDIA$PARTPREFIX"1
-	if ! (($VERO)); then
-#		while ! [ -e /dev/"$MEDIA"2 ]; do sleep 1; done
-		umount /dev/"$MEDIA$PARTPREFIX"2 2> /dev/null
-		mkfs.ext4 /dev/"$MEDIA$PARTPREFIX"2
-	fi
+	partprobe /dev/"$MEDIA"
+	# wait for the system to register the new partitions
+	while ! [ -e /dev/"$MEDIA$PARTPREFIX"1 ]; do
+		echo Waiting for /dev/"$MEDIA"
+		sleep 1
+	done
+	umount /dev/"$MEDIA$PARTPREFIX"2 2> /dev/null
+	mkfs.ext4 /dev/"$MEDIA$PARTPREFIX"2
 	# run this again to refresh things
-	partprobe &> /dev/null
+	partprobe /dev/"$MEDIA" &> /dev/null
 }
 
 if (($FORMAT)); then format; fi
 
 START=$(date +%s)
 
-# need to make vero filesystem before checking space on target to get proper size
-if (($VERO)); then
-	if [ -f "$BACKUPDIR/filesystem.tar.xz" ]; then
-		read -n1 -rsp "$BACKUPDIR/filesystem.tar.xz exists, press Y to overwrite, N to keep " ANSWER
-		if [[ $ANSWER =~ [Yy] ]]; then
-			rm "$BACKUPDIR/filesystem.tar.xz"
-		fi
-		echo
-	fi
-	if ! [ -f "$BACKUPDIR/filesystem.tar.xz" ]; then
-		### specify any space hogging directory not needed to boot the image
-		# eg home/osmc/Videos
-		BIGDIR="home/osmc/GitProjects"
-		# zip up the system files
-		echo Preparing to make tarball of system files
-		cd $BACKUPDIR/system/
-		SYSTEMSIZE=($(du -sB1 --exclude="$BIGDIR" "$BACKUPDIR/system"))
-		printf "%s%'u%s\n" "Packing " $((${SYSTEMSIZE[0]} / 1024 / 1024)) " MiB of system files - could take a while...."
-		tar -I "xz -0 -v" --exclude="$BIGDIR" -cf "$BACKUPDIR/filesystem.tar.xz" *
-	fi
-fi
-
-
 function restore(){
-	# check what partitions we have
-	PARTS=($(lsblk -blo NAME,FSTYPE,SIZE | grep "$MEDIA$PARTPREFIX\S\s"))
-	echo $PARTPREFIX
-	echo Partitions found: ${PARTS[@]}
 	for source in ${PARTStoRESTORE[@]}; do
 		PARTNAME=
-		if [ $source == "boot" ]; then
+		if [[ $source =~ "boot" ]]; then
 			PARTTYPE=vfat; PARTSIZEMIN=244000000
 			CPPARAM="--no-preserve=ownership"
 		elif [ $source == "system" ]; then
-			if (($VERO)); then
-				PARTTYPE=vfat
-				PARTSIZEMIN=($(du -sB1 "$BACKUPDIR/filesystem.tar.xz"))
-				# add size of kernel.img and dtb.img
-				PARTSIZEMIN[0]=$((${PARTSIZEMIN[0]} + 30000000 ))
-				CPPARAM="--no-preserve=ownership"
-			else
-				PARTTYPE=ext
-				if [ "$BACKUPDIR" == '/' ]; then
-					echo checking size of $BACKUPDIR
-					PARTSIZEMIN=($(du -xsB1 "$BACKUPDIR"))
-				else
-					echo checking size of "$BACKUPDIR/$source"
-					PARTSIZEMIN=($(du -xsB1 "$BACKUPDIR/$source"))
+			PARTTYPE=ext
+			if [ "$BACKUPDIR" == '/' ]; then
+				if [ $1 == "dry" ]; then
+					echo Checking size of working system
 				fi
-				CPPARAM="-x" # don't copy boot, media, mnt
+				PARTSIZEMIN=($(du -xsB1 "$BACKUPDIR"))
+			else
+				if [ $1 == "dry" ]; then
+					echo Checking size of "$BACKUPDIR/$source"
+				fi
+				PARTSIZEMIN=($(du -xsB1 "$BACKUPDIR/$source"))
 			fi
-			printf "%'u%s\n" $((${PARTSIZEMIN[0]} / 1024)) "KiB in $source backup"
+			CPPARAM="-x" # don't copy mounts boot, media, mnt
+			if [ $1 == "dry" ]; then
+				printf "%'u%s\n\n" $((${PARTSIZEMIN[0]} / 1024)) "KiB in $source"
+			fi
 		fi
 		for partindex in $(seq 1 3 "$((${#PARTS[@]} - 2))"); do
 			# do it only once if partition number has been specified
@@ -325,9 +306,10 @@ function restore(){
 				elif [ $partindex \< "$(( ($PARTNO - 1)*3 + 1 ))" ]; then continue
 				fi
 			fi
+			#echo  partition: ${PARTS[$partindex]}
 			if [[ ${PARTS[$partindex]} =~ "$PARTTYPE" ]]; then
-				PARTNAME=${PARTS[$(($partindex - 1))]}; echo $PARTNAME
-				PARTSIZE=${PARTS[$(($partindex + 1))]}; echo $PARTSIZE
+				PARTNAME=${PARTS[$(($partindex - 1))]}; #echo $PARTNAME
+				PARTSIZE=${PARTS[$(($partindex + 1))]}; #echo $PARTSIZE
 				if (( $PARTSIZE < $PARTSIZEMIN )); then
 					printf "%s%'u%s\n" "$PARTTYPE partition at $PARTNAME may be too small (" $(($PARTSIZE / 1024)) " KiB)"
 					read -n1 -rsp "Press Y to continue, any other key to skip" ANSWER
@@ -339,12 +321,13 @@ function restore(){
 					else
 						break
 					fi
-				else
+				elif [ $1 != "dry" ]; then
 					printf "%s%'u%s\n" "Found $PARTTYPE partition at $PARTNAME with enough space (" $(($PARTSIZE / 1024)) " KiB)"
 					read -n1 -rsp "Press Y to write $source to this partition, any other key to skip" ANSWER
 					if ! [[ $ANSWER =~ [Yy] ]]; then
 						echo
 						echo Skipping $PARTNAME partition ....
+						echo
 						PARTNAME=skip
 						continue
 					else
@@ -358,6 +341,8 @@ function restore(){
 			continue
 		fi
 		if [ $PARTNAME == "skip" ]; then continue; fi
+		PARTSFOUND=$(( $PARTSFOUND + 1 ))
+		if [ $1 == "dry" ]; then continue; fi
 
 		# check if target is already mounted - it will be if we've just formatted it
 		TARGET=$(findmnt -lo SOURCE,TARGET "/dev/$PARTNAME" | grep "[(media)|(mnt)]") # | sed 's/^.*\/[\(media\)|\(mnt\)]\/\(.*\)/\/\1\/\3/')
@@ -386,43 +371,80 @@ function restore(){
 		mount /dev/"$PARTNAME" /media/$source
 		#echo $(findmnt -l "/dev/$PARTNAME")
 		TARGET=/media/$source
-		
-		if (($VERO)); then
-			echo erasing all files on /dev/$PARTNAME
-			if [ $(ls "$TARGET" | wc -l) \> 0 ]; then rm -r "$TARGET"/*; fi
-			echo Copying "$BACKUPDIR"/filesystem.tar.xz to /dev/$PARTNAME
-			cp "$CPPARAM" "$BACKUPDIR"/filesystem.tar.xz "$TARGET"
+
+		if [ $source == 'system' ] && [ "$BACKUPDIR" == '/' ]; then
+			echo Copying root directory to /dev/$PARTNAME
+			EXCLUDES='--exclude=.gvfs'
+			# directories generated by the system
+			EXCLUDES+=' --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/run/* --exclude=/tmp/*'
+			# you probably don't want this directory - the equivalent of Windows *.chk files
+			EXCLUDES+=' --exclude=/lost+found'
+			# these mount directories should be excluded automatically by the -x switch in rsync
+			# but just to be sure
+			EXCLUDES+=' --exclude=/mnt/* --exclude=/media/*'
+			###		you may like to uncomment the next line - these directories should be unnecessary for a restore
+			#EXCLUDES+=' --exclude=/var/cache/* --exclude=/var/run/* --exclude=/var/tmp/*'
+			#cp -a "$CPPARAM" "$BACKUPDIR". "$TARGET"
+			rsync -axcH "$EXCLUDES" --delete --delete-excluded --info=progress2 --no-specials --no-devices "$BACKUPDIR" "$TARGET"
+		elif [ $source == 'boot' ] && (($VERO)); then
+			echo Copying Vero installer files to /dev/$PARTNAME
+			FILESFOUND=1
 			for img in kernel dtb; do
 				if [ -f "$BACKUPDIR/../$img.img" ]; then
 					echo Copying $img.img to /dev/$PARTNAME
 					cp "$BACKUPDIR/../$img.img" "$TARGET"
+				elif [ -f "$SCRIPTDIR/$img.img" ]; then
+					echo Copying $img.img to /dev/$PARTNAME
+					cp "$SCRIPTDIR/$img.img" "$TARGET"
 				else
-					echo "Can't find $img.img in ${BACKUPDIR%/*}."
-					echo For vero, you need copies of kernel.img and dtb.img from a recent install image.
-					echo Just copy these two files onto the SD card with filesystem.tar.xz
+					FILESFOUND=0
 				fi
 			done
+			if ! ((FILESFOUND)) ; then
+				echo "Can't find kernel.img and/or dtb.img in ${BACKUPDIR%/*}."
+				echo For Vero, you need copies of kernel.img and \(for Vero4k\) dtb.img from a recent install image.
+				echo Just copy these two files onto the FAT partition of your SD card or USB stick
+			fi
+			rm "$TARGET"/filesystem.sh &> /dev/null
+			echo Writing filesystem.sh to $TARGET
+			cat <<- EOF > "$TARGET"/filesystem.sh
+				mkdir /mnt/backup
+				DEVICE=\$( mount | grep "/mnt/boot" | awk '{ print \$1 }' )
+				DEVICE=\${DEVICE%1}2
+				mount \$DEVICE /mnt/backup
+				if [ -f /mnt/backup/filesystem.tar ]; then
+				  SYSTEMSIZE=\$(du -s /mnt/backup/filesystem.tar | awk '{ print \$1 }')
+				  cat /mnt/backup/filesystem.tar | pv -s \${SYSTEMSIZE}k -n | tar -xf - -C /mnt/root
+				elif [ -f /mnt/backup/filesystem.tar.xz ]; then
+				  SYSTEMSIZE=\$(du -s /mnt/backup/filesystem.tar.xz | awk '{ print \$1 }')
+				  cat /mnt/backup/filesystem.tar.xz | pv -s \${SYSTEMSIZE}k -n | tar -xJf - -C /mnt/root
+				# provide for restore direct from backup via ln -s <system> filesystem
+				elif [ -h /mnt/backup/filesystem ]; then
+				  SYSTEMSIZE=\$(du -s /mnt/backup/filesystem | awk '{ print \$1 }')
+				  find /mnt/backup/filesystem -type s -exec rm {} \\;
+				  tar -cf - -C /mnt/backup/filesystem ./ | pv -s \${SYSTEMSIZE}k -n | tar -xf - -C /mnt/root
+				else
+				  SYSTEMSIZE=\$(du -s /mnt/backup | awk '{ print \$1 }')
+				  find /mnt/backup -type s -exec rm {} \\;
+				  tar -cf - -C /mnt/backup ./ | pv -s \${SYSTEMSIZE}k -n | tar -xf - -C /mnt/root
+				fi
+				sync
+				umount /mnt/backup
+			EOF
+
 		else
-			if [ $source == 'system' ] && [ "$BACKUPDIR" == '/' ]; then
-				echo Copying root directory to /dev/$PARTNAME
-				EXCLUDES='--exclude=.gvfs'
-				# directories generated by the system
-				EXCLUDES+=' --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/run/* --exclude=/tmp/*'
-				# you probably don't want this directory - the equivalent of Windows *.chk files
-				EXCLUDES+=' --exclude=/lost+found'
-				# these mount directories should be excluded automatically by the mount process below
-				# but just to be sure
-				EXCLUDES+=' --exclude=/mnt/* --exclude=/media/*'
-				###		you may like to uncomment the next line - these directories should be unnecessary for a restore
-				#EXCLUDES+=' --exclude=/var/cache/* --exclude=/var/run/* --exclude=/var/tmp/*'
-				#cp -a "$CPPARAM" "$BACKUPDIR". "$TARGET"
-				rsync -axcH "$EXCLUDES" --delete --delete-excluded "$BACKUPDIR" "$TARGET"
+			if [ -f "$TARGET"/filesystem.tar ]; then
+				rm "$TARGET"/filesystem.tar
+			fi
+			echo Copying $BACKUPDIR/$source to /dev/$PARTNAME
+			if (($VERO)); then
+				tar -cf - -C "$BACKUPDIR/$source" ./ | pv -s ${PARTSIZEMIN[0]} | cat - > "$TARGET"/filesystem.tar
 			else
-				echo Copying $BACKUPDIR/$source to /dev/$PARTNAME
-				#cp -a "$CPPARAM" "$BACKUPDIR/$source/". "$TARGET"
-				rsync -axcH --delete "$BACKUPDIR/$source/" "$TARGET"
+				tar -cf - -C "$BACKUPDIR/$source" ./ | pv -s ${PARTSIZEMIN[0]} | tar -xf - -C "$TARGET"
 			fi
 		fi
+		echo unmounting "$TARGET"
+		echo
 		umount "$TARGET"
 		if [ -d "$TARGET" ]; then rmdir "$TARGET"; fi
 		umount /media/sdcard/$source &> /dev/null && \
@@ -432,23 +454,38 @@ function restore(){
 }
 
 RESTORED=0
-while [ $RESTORED \< ${#PARTStoRESTORE[@]} ]; do
-	restore
-	rmdir /media/sdcard &> /dev/null
-	if [ $RESTORED \< ${#PARTStoRESTORE[@]} ]; then
-		echo Not all partitions were restored
-		echo "Partitions on $MEDIA are as follows"
-		parted /dev/$MEDIA print
+PARTSFOUND=0
+while [ $PARTSFOUND \< ${#PARTStoRESTORE[@]} ]; do
+	# check what partitions we have
+	PARTS=($(lsblk -blo NAME,FSTYPE,SIZE | grep "$MEDIA$PARTPREFIX\S\s"))
+	echo Looking for existing partitions on $DEVICE
+	echo Partitions found: $((${#PARTS[@]}/3)) ${PARTS[@]}
+	echo
+	if (( ${#PARTS[@]}/3 >= ${#PARTStoRESTORE[@]} )); then
+		restore dry
+	else
+		echo Not enough partitions on $DEVICE
+	fi
+	if [ $PARTSFOUND \< ${#PARTStoRESTORE[@]} ]; then
+		echo Could not find suitable partitions for ${PARTStoRESTORE[@]}
+		echo "Partitions on $DEVICE are as follows"
+		parted /dev/$DEVICE print
 		read -n1 -rsp "Do you want to re-format the card and try again (Y/N)?" ANSWER
 		echo
 		if [[ $ANSWER =~ [Yy] ]]; then
 			format
 			START=$(date +%s)
+			PARTSFOUND=0
 		else
 			break
 		fi
 	fi
 done
+restore all
+rmdir /media/sdcard &> /dev/null
+if [ $RESTORED \< ${#PARTStoRESTORE[@]} ]; then
+	echo WARNING: only $RESTORED of ${#PARTStoRESTORE[@]} partitions were restored
+fi
 
 ELAPSED=$(($(date +%s) - $START))
 echo Time to restore: $(date -d@${ELAPSED} -u +%Hh:%Mm:%Ss)
